name: Test

on:
  pull_request:
    branches:  
    - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - run: yarn 
    - run: yarn test --coverage
    env: 
     CI: true
